# This is a generated file. Not intended for manual editing.
services:
  shanesstorage.web:
    build:
      context: "C:\\Users\\shane\\Documents\\repos\\ShanesStorage"
      dockerfile: "ShanesStorage.Web/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/ShanesStorage.Web.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "shanesstorage.web:dev"
    ports: []
    volumes:
    - "C:\\Users\\shane\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\shane\\Documents\\repos\\ShanesStorage\\ShanesStorage.Web:/app:rw"
    - "C:\\Users\\shane\\Documents\\repos\\ShanesStorage:/src:rw"
    working_dir: "/app"
