services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - ./azurite:/workspace
  shanesstorage.web:
    image: shanesstorage.web
    container_name: ShanesStorage.Web
    ports:
      - 8080:8080
    build:

      context: .
      dockerfile: ShanesStorage.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8080
      - ASPNETCORE_HTTPS_PORT=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  
  shanesstorage.app:
    image: shanesstorage.app
    container_name: ShanesStorage.App
    build:
      context: ./ShanesStorage.App
      dockerfile: Dockerfile
    ports:
      - 420:80
