services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - ./azurite:/workspace

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/database:/var/lib/sqlserver/data
      - ./.containers/database:/var/lib/sqlserver/log
      - ./.containers/database:/var/lib/sqlserver/secrets
    ports:
      - 1433:1433

  shanesstorage.web:
    image: shanesstorage.web
    container_name: ShanesStorage.Web
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: ShanesStorage.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8080
      - ASPNETCORE_HTTPS_PORT=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  
  shanesstorage.app:
    image: shanesstorage.app
    container_name: ShanesStorage.App
    build:
      context: ./ShanesStorage.App
      dockerfile: Dockerfile
    ports:
      - 420:80
